version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Pod Spec Update"
          command: "bash spec_update.sh"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
